Environment:
    targets:
        1:
            class: 'simple'
            parameters:
                position: [5, 0, 5] # x, y, z
                velocity: [-1, 0, 3] # vx, vy, vz
        2:
            class: 'accelerating'
            parameters:
                position: [-1, 2, -1] # x, y, z
                velocity: [0, 0, 0] # vx, vy, vz
                acceleration: [1, 0, 2]
        3:
            class: 'circled'
            parameters:
                position: [-1, 0, 0] # x, y, z
                velocity: [0, 0, 1] # vx, vy, vz
                center: [0, 0, 0]
    projectiles:
        class: 'guided missile'
        parameters:
            position: [0, 0, 0]
            explosion_distance: 0.1
            max_velocity: 5
    time_step: 0.01