Environment:
    targets:
        1:
            trajectory_type: 'uniform'
            trajectory_arguments:
                position: [5, 0, 5] # x, y, z
                velocity: [-1, 0, 3] # vx, vy, vz
        2:
            trajectory_type: 'accelerating'
            trajectory_arguments:
                position: [-1, 2, -1] # x, y, z
                velocity: [0, 0, 0] # vx, vy, vz
                acceleration: [1, 0, 2]
        3:
            trajectory_type: 'circled'
            trajectory_arguments:
                position: [-1, 0, 0] # x, y, z
                velocity: [0, 0, 1] # vx, vy, vz
                center: [0, 0, 0]
        4:
            trajectory_type: 'complex'
            trajectory_arguments:
                position: [-1, 0, 0] # x, y, z
                trajectories:
                    1:
                        trajectory_duration: 2
                        class: 'uniform'
                        parameters:
                            position: None
                            velocity: [-1, -1, -1]
                    2:
                        trajectory_duration: 2
                        class: 'uniform'
                        parameters:
                            position: None
                            velocity: [2, 0, 1]
                    3:
                        trajectory_duration: 4
                        class: 'circled'
                        parameters:
                            position: None
                            center: [0, 0, 0]
                            velocity: [-1, 0, -1]
                    4:
                        trajectory_duration: 2
                        class: 'accelerating'
                        parameters:
                            position: None
                            velocity: None
                            acceleration: [1, 0, 1]
                                
    projectiles:
        class: 'guided missile'
        parameters:
            position: [0, 0, 0]
            explosion_range: 0.3
            trigger_distance: 0.1
            max_velocity: 5

    time_step: 0.01
