Environment:
    targets:
        0:
            trajectory_type: 'uniform'
            trajectory_arguments:
                position: [2000, 4500, 500] # x, y, z
                velocity: [400, 0, 0] # vx, vy, vz
        1:
            trajectory_type: 'uniform'
            trajectory_arguments:
                position: [2000, 4700, 500] # x, y, z
                velocity: [400, 0, 0] # vx, vy, vz
#        2:
#            trajectory_type: 'uniform'
#            trajectory_arguments:
#                position: [4500, 4000, 800] # x, y, z
#                velocity: [0, 300, 0] # vx, vy, vz
#        3:
#            trajectory_type: 'circled'
#            trajectory_arguments:
#                position: [2000, 5000, 1000] # x, y, z
#                velocity: [0, 800, 0] # vx, vy, vz
#                center: [3000, 5000, 0]
#         0:
#             trajectory_type: 'complex'
#             trajectory_arguments:
#                 position: [2000, 4000, 400] # x, y, z
#                 trajectories:
#                     0:
#                         trajectory_duration: 2
#                         class: 'uniform'
#                         parameters:
#                             position: null
#                             velocity: [200, 200, 0]
#                     1:
#                         trajectory_duration: 2
#                         class: 'uniform'
#                         parameters:
#                             position: null
#                             velocity: [0, -300, 0]

    time_step: 0.005

Pbu:
    time_step: 0.005
    add_distance: 300
    launchers:
        1:
            launcher_pos: [3000, 3000, 0]
            missile_amount: 5
            speed: 5000
            missile_type: 'guided missile'
            trigger_distance: 10.0
            explosion_range: 100.0
        2:
            launcher_pos: [8000, 7000, 0]
            missile_amount: 5
            speed: 5000
        3:
            launcher_pos: [ 5000, 5000, 0 ]
            missile_amount: 5
            speed: 5000


Locator:
    1:
        time_step: 0.005
        coordinates:
            x: 4000
            y: 5000
            z: 0
        omega_az: 15
        omega_el: 8
        r_max: 2000
        dr: 1
    2:
        time_step: 0.005
        coordinates:
            x: 6000
            y: 5000
            z: 0
        omega_az: 15
        omega_el: 8
        r_max: 2000
        dr: 1