Environment:
    targets:
        0:
            trajectory_type: 'uniform'
            trajectory_arguments:
                position: [4000, 4000, 150] # x, y, z
                velocity: [300, 100, 0] # vx, vy, vz
        1:
            trajectory_type: 'uniform'
            trajectory_arguments:
                position: [5000, 6000, 100] # x, y, z
                velocity: [-20, -300, 0] # vx, vy, vz
        2:
            trajectory_type: 'uniform'
            trajectory_arguments:
                position: [4500, 3000, 200] # x, y, z
                velocity: [50, 300, 0] # vx, vy, vz
        # 1:
        #     trajectory_type: 'accelerating'
        #     trajectory_arguments:
        #         position: [-1, 2, -1] # x, y, z
        #         velocity: [0, 0, 0] # vx, vy, vz
        #         acceleration: [1, 0, 2]
        # 2:
        #     trajectory_type: 'circled'
        #     trajectory_arguments:
        #         position: [-1, 0, 0] # x, y, z
        #         velocity: [0, 0, 1] # vx, vy, vz
        #         center: [0, 0, 0]
        # 3:
        #     trajectory_type: 'complex'
        #     trajectory_arguments:
        #         position: [-1, 0, 0] # x, y, z
        #         trajectories:
        #             0:
        #                 trajectory_duration: 2
        #                 class: 'uniform'
        #                 parameters:
        #                     position: null
        #                     velocity: [-1, -1, -1]
        #             1:
        #                 trajectory_duration: 2
        #                 class: 'uniform'
        #                 parameters:
        #                     position: null
        #                     velocity: [2, 0, 1]
        #             2:
        #                 trajectory_duration: 4
        #                 class: 'circled'
        #                 parameters:
        #                     position: null
        #                     center: [0, 0, 0]
        #                     velocity: [-1, 0, -1]
        #             3:
        #                 trajectory_duration: 2
        #                 class: 'accelerating'
        #                 parameters:
        #                     position: null
        #                     velocity: null
        #                     acceleration: [1, 0, 1]
                                
    # projectiles:
    #     class: 'guided missile'
    #     parameters:
    #         position: [0, 0, 0]
    #         explosion_range: 0.3
    #         trigger_distance: 0.1
    #         max_velocity: 5

    time_step: 0.001

Pbu:
    add_distance: 300
    launchers:
        1:
            launcher_pos: [3000, 3000, 0]
            missile_amount: 5

Locator: 
    time_step: 0.005
    coordinates:
        x: 5000
        y: 5000
        z: 0
    omega_az: 15
    omega_el: 8
    r_max: 2000
    dr: 1